const T = {
  en: {
    page_title: "Dr. Ludmila Bičanová | Veterinary Oncology Specialist",
    nav_about: "About", nav_credentials: "Credentials", nav_services: "Services",
    nav_career: "Career", nav_research: "Research", nav_locations: "Locations", nav_contact: "Contact",
    hero_eyebrow: "EBVS® European Veterinary Specialist",
    hero_title: "Veterinary Oncology",
    hero_subtitle: "Expert Cancer Care for Your Companion Animal",
    hero_desc: "Specialist consultations in Medical & Radiation Oncology · Switzerland & Czech Republic",
    hero_cta1: "Book a Consultation", hero_cta2: "Learn More",
    hero_b1: "Medical Oncology", hero_b2: "Radiation Oncology", hero_b3: "15+ Years Experience",
    hero_scroll: "Scroll",
    about_eyebrow: "About",
    about_name: "Dr. Ludmila Bičanová",
    about_creds: "MVDr. · Dip. ECVIM-CA (Onc) · MSc (Clin Onc) · PhD · MRCVS",
    about_badge_name: "Dr. Ludmila Bičanová",
    about_badge_creds: "Medical Director · AniCura AOI, Switzerland",
    about_p1: "MVDr. Ludmila Bičanová is an EBVS® European Veterinary Specialist in both Veterinary Oncology and Radiation Oncology, and a Diplomate of the European College of Veterinary Internal Medicine – Companion Animals (ECVIM-CA). She also holds RCVS recognition as a Recognised Specialist in Veterinary Oncology.",
    about_p2: "As Medical Director at AniCura AOI – Animal Oncology and Imaging Center in Hünenberg, Switzerland, she leads a multidisciplinary team at one of Europe's premier veterinary oncology centres, combining state-of-the-art diagnostic imaging with comprehensive cancer treatment.",
    about_p3: "With over 15 years of clinical experience spanning the Czech Republic, Austria, and Switzerland, Dr. Bičanová is dedicated to providing the highest standard of specialist care — guiding families with clarity and compassion through every stage of their pet's cancer journey.",
    stat1_n: "15+", stat1_l: "Years of Clinical Experience",
    stat2_n: "3",   stat2_l: "Countries of Practice",
    stat3_n: "2",   stat3_l: "Oncology Specialities",
    cred_eyebrow: "Qualifications", cred_title: "Credentials & Certifications",
    cred_sub: "Recognised by the highest European and international veterinary bodies",
    c1t: "Dip. ECVIM-CA (Oncology)", c1b: "Diplomate of the European College of Veterinary Internal Medicine – Companion Animals, Oncology track",
    c2t: "+ Radiation Oncology",      c2b: "Additional Diplomate qualification in Radiation Oncology (ECVIM-CA / ECVDI)",
    c3t: "EBVS® European Specialist", c3b: "European Board of Veterinary Specialisation in Veterinary Oncology and Radiation Oncology",
    c4t: "RCVS Specialist",           c4b: "Royal College of Veterinary Surgeons Recognised Specialist in Veterinary Oncology",
    c5t: "MSc (Clinical Oncology)",   c5b: "Master of Science in Clinical Oncology",
    c6t: "PhD",                        c6b: "Doctor of Philosophy in Veterinary Medicine / Oncology",
    c7t: "MRCVS",                      c7b: "Member of the Royal College of Veterinary Surgeons",
    c8t: "MVDr.",                      c8b: "Doctor of Veterinary Medicine, University of Veterinary Sciences Brno, Czech Republic (2009)",
    spec_eyebrow: "Expertise", spec_title: "Areas of Specialisation",
    spec_sub: "Comprehensive oncological care combining medical and radiation expertise",
    s1t: "Medical Oncology",     s1b: "Diagnosis, staging, and medical management of cancer in companion animals — including chemotherapy, immunotherapy and targeted therapies for a wide range of tumour types.",
    s2t: "Radiation Oncology",   s2b: "Specialist consultation and planning for radiation therapy, including curative and palliative protocols, in close collaboration with referring veterinarians and radiation centres across Europe.",
    s3t: "Lymphoma Diagnostics", s3b: "Expert diagnosis and staging of canine and feline lymphoma, with focus on advanced modalities including flow cytometry and molecular profiling.",
    s4t: "Diagnostic Oncology",  s4b: "Integration of advanced imaging (CT, MRI, ultrasound) with cytology and histopathology for precise tumour diagnosis, staging, and treatment planning.",
    svc_eyebrow: "Services", svc_title: "Consultation Services",
    svc_sub: "Personalised specialist care, available in Switzerland and the Czech Republic",
    sv1t: "Initial Oncology Consultation", sv1b: "Comprehensive first evaluation including history review, physical examination, diagnostic workup planning, and staging — with a clear treatment roadmap tailored to each patient.",
    sv2t: "Second Opinion",               sv2b: "Independent specialist review of existing diagnoses, pathology reports, and treatment plans. Confidence and clarity when families face difficult cancer-related decisions.",
    sv3t: "Treatment Planning",           sv3b: "Evidence-based, individualised treatment plans integrating the latest protocols in chemotherapy, radiation therapy, and multimodal oncological management.",
    sv4t: "Radiation Therapy Consultation", sv4b: "Expert guidance on radiation therapy candidacy, treatment options, expected outcomes, and coordination with radiation centres across Europe.",
    sv5t: "Palliative & Supportive Care", sv5b: "Quality-of-life-centred management where cure is not achievable — focusing on comfort, pain control, and compassionate family support.",
    sv6t: "Remote Consultation",          sv6b: "Telemedicine consultations for case review and specialist advice, enabling collaboration with veterinarians across Switzerland, the Czech Republic, and beyond.",
    svc_link: "Learn more →",
    career_eyebrow: "Journey", career_title: "Professional Career",
    career_sub: "Over 15 years of progressive expertise in veterinary internal medicine and oncology",
    cr1y: "2009",      cr1t: "Graduation — VFU Brno",           cr1b: "Doctor of Veterinary Medicine, University of Veterinary Sciences Brno, Czech Republic",
    cr2y: "2009–2011", cr2t: "Jaggy Clinic, Brno",               cr2b: "Rotation internship, then assistant in the internal medicine department",
    cr3y: "2011–2015", cr3t: "Animal Clinic Bílá Hora, Prague",  cr3b: "Clinical focus on internal medicine and oncology in dogs and cats at a leading private referral centre",
    cr4y: "2015–2022", cr4t: "Vetmeduni Vienna",                  cr4b: "Internal medicine department, Small Animal Teaching Hospital; from 2017: ECVIM-CA Oncology residency under Prof. Miriam Kleiter",
    cr5y: "2022",      cr5t: "Diplomate ECVIM-CA (Oncology)",    cr5b: "Successful completion of the ECVIM-CA Oncology board examination",
    cr6y: "2022–Present", cr6t: "Medical Director — AniCura AOI", cr6b: "Leading the clinical team at AniCura AOI – Animal Oncology and Imaging Center, Hünenberg, Switzerland",
    res_eyebrow: "Research", res_title: "Academic & Scientific Contributions",
    res_sub: "Advancing veterinary oncology through research, education, and publication",
    r1v: "Veterinary Oncology · BioMed Central",
    r1t: "L-Asparaginase in Canine Lymphoma",
    r1b: "Co-authored pilot study investigating intravenous administration of monomeric L-asparaginase to dogs with multicentric lymphoma, contributing to novel treatment protocol development.",
    r2v: "Canine Lymphoma Meeting · Invited Speaker",
    r2t: "Canine Lymphoma Diagnostics & Staging",
    r2b: "Invited presentation on advanced diagnostic modalities for canine lymphoma staging, including flow cytometry and molecular diagnostics.",
    r3v: "Frontiers in Veterinary Science · 2025",
    r3t: "Editorial — Oncology in Veterinary Medicine",
    r3b: "Contributed editorial to the Oncology section addressing current challenges and advances in veterinary oncology.",
    roles_eyebrow: "Leadership", roles_title: "Professional Roles",
    roles_sub: "Active contributor to the advancement of veterinary oncology across Europe",
    ro1t: "Medical Director",                        ro1o: "AniCura AOI – Animal Oncology and Imaging Center, Switzerland",
    ro2t: "Chair, Radiation Oncology Education & Credentials Committee", ro2o: "ECVIM-CA / ECVDI Joint Committee",
    ro3t: "Head, Oncology Section",                  ro3o: "Czech Association for Small Animal Medicine (ČAVLMZ)",
    ro4t: "Vice President (2018–)",                   ro4o: "Czech Association for Small Animal Medicine (ČAVLMZ)",
    loc_eyebrow: "Locations", loc_title: "Consultation Locations",
    loc_sub: "Specialist services available in Switzerland and the Czech Republic",
    l1_country: "Switzerland", l1_clinic: "AniCura AOI – Animal Oncology and Imaging Center", l1_addr: "Hünenberg, Canton Zug, Switzerland",
    l1_desc: "One of Europe's leading veterinary oncology and imaging centres offering CT, MRI, ultrasound, radiation therapy, and comprehensive medical oncology.",
    l2_country: "Czech Republic", l2_clinic: "Specialist Consultations", l2_addr: "Available on request — Czech Republic",
    l2_desc: "Consultations available for referring veterinarians and pet owners in the Czech Republic. Contact us for scheduling information.",
    l3_country: "Remote / Telemedicine", l3_clinic: "Online Consultations", l3_addr: "Available across Europe",
    l3_desc: "Case consultation and specialist advice available remotely for veterinarians across Switzerland, the Czech Republic, and Europe.",
    contact_eyebrow: "Get in Touch", contact_title: "Book a Consultation",
    contact_sub: "For specialist referrals, consultation requests, or general enquiries, please reach out via the form below.",
    ci1_label: "Primary Clinic", ci1_val: "AniCura AOI, Hünenberg, Switzerland",
    ci2_label: "Consultations", ci2_val: "Switzerland & Czech Republic",
    ci3_label: "Languages", ci3_val: "English · Deutsch · Čeština",
    ci4_label: "Response time", ci4_val: "Within 2 business days",
    f_name: "Full Name", f_email: "Email Address", f_phone: "Phone Number (optional)",
    f_type: "Consultation Type", f_t0: "Select consultation type",
    f_t1: "Initial Oncology Consultation", f_t2: "Second Opinion",
    f_t3: "Radiation Therapy Consultation", f_t4: "Remote / Telemedicine", f_t5: "Other",
    f_loc: "Preferred Location", f_l0: "Select location",
    f_l1: "Switzerland", f_l2: "Czech Republic", f_l3: "Remote / Telemedicine",
    f_msg: "Tell us about your pet and how we can help",
    f_submit: "Send Enquiry",
    f_note: "All enquiries are treated with strict confidentiality. We aim to respond within 2 business days.",
    ft_tagline: "European Veterinary Specialist in Oncology & Radiation Oncology",
    ft_nav: "Navigation", ft_contact: "Contact", ft_lang: "Language",
    ft_rights: "© 2025 Dr. Ludmila Bičanová. All rights reserved.",
    ft_disclaimer: "This website is for informational purposes only. For medical emergencies, please contact your local veterinarian immediately.",
  },
  de: {
    page_title: "Dr. Ludmila Bičanová | Veterinär-Onkologie Spezialistin",
    nav_about: "Über mich", nav_credentials: "Qualifikationen", nav_services: "Leistungen",
    nav_career: "Karriere", nav_research: "Forschung", nav_locations: "Standorte", nav_contact: "Kontakt",
    hero_eyebrow: "EBVS® Europäische Veterinärspezialistin",
    hero_title: "Veterinär-Onkologie",
    hero_subtitle: "Fachkundige Krebsversorgung für Ihr Haustier",
    hero_desc: "Spezialkonsultationen in medizinischer Onkologie & Strahlentherapie · Schweiz & Tschechische Republik",
    hero_cta1: "Termin vereinbaren", hero_cta2: "Mehr erfahren",
    hero_b1: "Medizinische Onkologie", hero_b2: "Strahlentherapie", hero_b3: "15+ Jahre Erfahrung",
    hero_scroll: "Scrollen",
    about_eyebrow: "Über mich",
    about_name: "Dr. Ludmila Bičanová",
    about_creds: "MVDr. · Dip. ECVIM-CA (Onk.) · MSc (Klin. Onk.) · PhD · MRCVS",
    about_badge_name: "Dr. Ludmila Bičanová",
    about_badge_creds: "Ärztliche Direktorin · AniCura AOI, Schweiz",
    about_p1: "MVDr. Ludmila Bičanová ist EBVS® Europäische Veterinärspezialistin für Veterinär-Onkologie und Strahlentherapie sowie Diplomate des European College of Veterinary Internal Medicine – Companion Animals (ECVIM-CA). Sie ist zudem RCVS-anerkannte Spezialistin für Veterinär-Onkologie.",
    about_p2: "Als Ärztliche Direktorin am AniCura AOI – Animal Oncology and Imaging Center in Hünenberg, Schweiz, leitet sie ein multidisziplinäres Team an einem der führenden veterinäronkologischen Zentren Europas — mit modernster Bildgebungsdiagnostik und umfassender Krebsbehandlung.",
    about_p3: "Mit über 15 Jahren klinischer Erfahrung in der Tschechischen Republik, Österreich und der Schweiz ist Dr. Bičanová dem höchsten Spezialistenstandard verpflichtet — sie begleitet Tierhalter mit Klarheit und Einfühlungsvermögen durch jede Phase der onkologischen Behandlung.",
    stat1_n: "15+", stat1_l: "Jahre klinische Erfahrung",
    stat2_n: "3",   stat2_l: "Tätigkeitsländer",
    stat3_n: "2",   stat3_l: "Onkologische Fachgebiete",
    cred_eyebrow: "Qualifikationen", cred_title: "Abschlüsse & Zertifizierungen",
    cred_sub: "Anerkannt von den höchsten europäischen und internationalen Veterinärorganisationen",
    c1t: "Dip. ECVIM-CA (Onkologie)", c1b: "Diplomate des European College of Veterinary Internal Medicine – Companion Animals, Onkologie",
    c2t: "+ Strahlentherapie",          c2b: "Zusätzliche Diplomate-Qualifikation in Strahlentherapie (ECVIM-CA / ECVDI)",
    c3t: "EBVS® Europäische Spezialistin", c3b: "European Board of Veterinary Specialisation in Veterinär-Onkologie und Strahlentherapie",
    c4t: "RCVS Spezialistin",          c4b: "Anerkannte Spezialistin des Royal College of Veterinary Surgeons in Veterinär-Onkologie",
    c5t: "MSc (Klinische Onkologie)",  c5b: "Master of Science in klinischer Onkologie",
    c6t: "PhD",                         c6b: "Doktor der Philosophie in Veterinärmedizin / Onkologie",
    c7t: "MRCVS",                       c7b: "Mitglied des Royal College of Veterinary Surgeons",
    c8t: "MVDr.",                       c8b: "Doktor der Veterinärmedizin, Veterinärmedizinische Universität Brno, Tschechische Republik (2009)",
    spec_eyebrow: "Fachkompetenz", spec_title: "Fachgebiete",
    spec_sub: "Umfassende onkologische Versorgung mit Expertise in medizinischer Onkologie und Strahlentherapie",
    s1t: "Medizinische Onkologie",  s1b: "Diagnose, Staging und medizinische Behandlung von Krebs bei Heimtieren — einschließlich Chemotherapie, Immuntherapie und zielgerichteter Therapien für ein breites Spektrum an Tumorarten.",
    s2t: "Strahlentherapie",         s2b: "Fachkonsultation und Planung von Strahlentherapien, einschließlich kurativer und palliativer Protokolle, in enger Zusammenarbeit mit Überweisern und Strahlenzentren in Europa.",
    s3t: "Lymphom-Diagnostik",       s3b: "Fachkundige Diagnose und Staging von kaninem und felinem Lymphom mit Fokus auf Durchflusszytometrie und molekulares Profiling.",
    s4t: "Diagnostische Onkologie",  s4b: "Integration fortgeschrittener Bildgebung (CT, MRT, Ultraschall) mit Zytologie und Histopathologie für präzise Tumordiagnose und Therapieplanung.",
    svc_eyebrow: "Leistungen", svc_title: "Konsultationsleistungen",
    svc_sub: "Persönliche Fachversorgung in der Schweiz und der Tschechischen Republik",
    sv1t: "Erste onkologische Konsultation", sv1b: "Umfassende Erstbeurteilung mit Anamnese, klinischer Untersuchung, Diagnostikplanung und Staging — mit individuellem Behandlungsplan.",
    sv2t: "Zweitmeinung",                     sv2b: "Unabhängige Fachbeurteilung bestehender Diagnosen, Pathologieberichte und Behandlungspläne. Klarheit bei schwierigen onkologischen Entscheidungen.",
    sv3t: "Therapieplanung",                  sv3b: "Evidenzbasierte, individualisierte Behandlungspläne unter Einbeziehung aktueller Protokolle in Chemotherapie, Strahlentherapie und multimodaler Onkologie.",
    sv4t: "Strahlentherapie-Konsultation",   sv4b: "Fachkundige Beratung zu Eignung, Optionen, erwarteten Ergebnissen und Koordination mit Strahlenzentren in Europa.",
    sv5t: "Palliativ- & Supportivversorgung", sv5b: "Lebensqualitätsorientierte Versorgung bei nicht heilbaren Patienten — Fokus auf Komfort, Schmerzmanagement und Unterstützung der Tierhalter.",
    sv6t: "Fernkonsultation",                 sv6b: "Telemedizinische Beratung für Fallbesprechungen in der Schweiz, der Tschechischen Republik und darüber hinaus.",
    svc_link: "Mehr erfahren →",
    career_eyebrow: "Werdegang", career_title: "Beruflicher Werdegang",
    career_sub: "Über 15 Jahre progressive Expertise in der veterinärmedizinischen Inneren Medizin und Onkologie",
    cr1y: "2009",        cr1t: "Abschluss — VFU Brno",              cr1b: "Doktor der Veterinärmedizin, Veterinärmedizinische Universität Brno, Tschechische Republik",
    cr2y: "2009–2011",   cr2t: "Jaggy Klinik, Brno",                cr2b: "Rotationsassistenz, dann Assistenzärztin in der Abteilung für Innere Medizin",
    cr3y: "2011–2015",   cr3t: "Animal Clinic Bílá Hora, Prag",     cr3b: "Klinischer Schwerpunkt Innere Medizin und Onkologie bei Hunden und Katzen an einer führenden Überweisungsklinik",
    cr4y: "2015–2022",   cr4t: "Vetmeduni Wien",                    cr4b: "Abteilung für Innere Medizin, Kleintierklinik; ab 2017: ECVIM-CA Onkologie-Residency unter Prof. Miriam Kleiter",
    cr5y: "2022",        cr5t: "Diplomate ECVIM-CA (Onkologie)",    cr5b: "Erfolgreicher Abschluss der ECVIM-CA Onkologie-Boardprüfung",
    cr6y: "2022–heute",  cr6t: "Ärztliche Direktorin — AniCura AOI", cr6b: "Leitung des klinischen Teams am AniCura AOI – Animal Oncology and Imaging Center, Hünenberg, Schweiz",
    res_eyebrow: "Forschung", res_title: "Wissenschaftliche Beiträge",
    res_sub: "Förderung der Veterinäronkologie durch Forschung, Lehre und Publikation",
    r1v: "Veterinary Oncology · BioMed Central",
    r1t: "L-Asparaginase bei kaninem Lymphom",
    r1b: "Co-Autorin einer Pilotstudie zur intravenösen Gabe von monomerem L-Asparaginase bei Hunden mit multizentrischem Lymphom — Beitrag zur Entwicklung neuer Behandlungsprotokolle.",
    r2v: "Canine Lymphoma Meeting · Eingeladene Referentin",
    r2t: "Diagnostik & Staging kanines Lymphom",
    r2b: "Eingeladener Vortrag über moderne Diagnoseverfahren für das Staging des kaninen Lymphoms, einschließlich Durchflusszytometrie und Molekulardiagnostik.",
    r3v: "Frontiers in Veterinary Science · 2025",
    r3t: "Editorial — Onkologie in der Veterinärmedizin",
    r3b: "Beitrag zu aktuellen Herausforderungen und Fortschritten in der Veterinäronkologie.",
    roles_eyebrow: "Führungsrollen", roles_title: "Berufliche Positionen",
    roles_sub: "Aktiver Beitrag zur Weiterentwicklung der Veterinäronkologie in Europa",
    ro1t: "Ärztliche Direktorin",                          ro1o: "AniCura AOI – Animal Oncology and Imaging Center, Schweiz",
    ro2t: "Vorsitzende, Ausbildungskomitee Strahlentherapie", ro2o: "ECVIM-CA / ECVDI Gemeinsames Komitee",
    ro3t: "Leiterin, Onkologiesektion",                    ro3o: "Tschechischer Verband für Kleintiermedizin (ČAVLMZ)",
    ro4t: "Vizepräsidentin (seit 2018)",                    ro4o: "Tschechischer Verband für Kleintiermedizin (ČAVLMZ)",
    loc_eyebrow: "Standorte", loc_title: "Konsultationsstandorte",
    loc_sub: "Fachleistungen in der Schweiz und der Tschechischen Republik",
    l1_country: "Schweiz", l1_clinic: "AniCura AOI – Animal Oncology and Imaging Center", l1_addr: "Hünenberg, Kanton Zug, Schweiz",
    l1_desc: "Eines der führenden veterinäronkologischen und bildgebenden Zentren Europas mit CT, MRT, Ultraschall, Strahlentherapie und umfassender medizinischer Onkologie.",
    l2_country: "Tschechische Republik", l2_clinic: "Spezialkonsultationen", l2_addr: "Auf Anfrage — Tschechische Republik",
    l2_desc: "Konsultationen für überweisende Tierärzte und Tierhalter in der Tschechischen Republik. Kontaktieren Sie uns für Terminvereinbarungen.",
    l3_country: "Fernkonsultation / Telemedizin", l3_clinic: "Online-Konsultationen", l3_addr: "Europaweit verfügbar",
    l3_desc: "Fallbesprechung und Fachberatung per Telemedizin für Tierärzte in der Schweiz, der Tschechischen Republik und Europa.",
    contact_eyebrow: "Kontakt", contact_title: "Termin vereinbaren",
    contact_sub: "Für Überweisungen, Konsultationsanfragen oder allgemeine Anfragen wenden Sie sich über das folgende Formular an uns.",
    ci1_label: "Hauptklinik", ci1_val: "AniCura AOI, Hünenberg, Schweiz",
    ci2_label: "Konsultationen", ci2_val: "Schweiz & Tschechische Republik",
    ci3_label: "Sprachen", ci3_val: "English · Deutsch · Čeština",
    ci4_label: "Antwortzeit", ci4_val: "Innerhalb von 2 Werktagen",
    f_name: "Vollständiger Name", f_email: "E-Mail-Adresse", f_phone: "Telefonnummer (optional)",
    f_type: "Konsultationsart", f_t0: "Konsultationsart wählen",
    f_t1: "Erste onkologische Konsultation", f_t2: "Zweitmeinung",
    f_t3: "Strahlentherapie-Konsultation", f_t4: "Fernkonsultation / Telemedizin", f_t5: "Sonstiges",
    f_loc: "Bevorzugter Standort", f_l0: "Standort wählen",
    f_l1: "Schweiz", f_l2: "Tschechische Republik", f_l3: "Fernkonsultation / Telemedizin",
    f_msg: "Erzählen Sie uns von Ihrem Tier und wie wir helfen können",
    f_submit: "Anfrage senden",
    f_note: "Alle Anfragen werden streng vertraulich behandelt. Wir antworten innerhalb von 2 Werktagen.",
    ft_tagline: "Europäische Veterinärspezialistin für Onkologie & Strahlentherapie",
    ft_nav: "Navigation", ft_contact: "Kontakt", ft_lang: "Sprache",
    ft_rights: "© 2025 Dr. Ludmila Bičanová. Alle Rechte vorbehalten.",
    ft_disclaimer: "Diese Website dient nur zu Informationszwecken. Wenden Sie sich bei Notfällen sofort an Ihren Tierarzt.",
  },
  cs: {
    page_title: "Dr. Ludmila Bičanová | Specialistka veterinární onkologie",
    nav_about: "O mně", nav_credentials: "Kvalifikace", nav_services: "Služby",
    nav_career: "Kariéra", nav_research: "Věda", nav_locations: "Místa", nav_contact: "Kontakt",
    hero_eyebrow: "EBVS® Evropská veterinární specialistka",
    hero_title: "Veterinární onkologie",
    hero_subtitle: "Odborná onkologická péče pro vašeho mazlíčka",
    hero_desc: "Specializované konzultace v medicínské onkologii a radiační onkologii · Švýcarsko & Česká republika",
    hero_cta1: "Objednat konzultaci", hero_cta2: "Zjistit více",
    hero_b1: "Medicínská onkologie", hero_b2: "Radiační onkologie", hero_b3: "15+ let zkušeností",
    hero_scroll: "Rolovat",
    about_eyebrow: "O mně",
    about_name: "Dr. Ludmila Bičanová",
    about_creds: "MVDr. · Dip. ECVIM-CA (Onk.) · MSc (Klin. Onk.) · PhD · MRCVS",
    about_badge_name: "Dr. Ludmila Bičanová",
    about_badge_creds: "Medicínská ředitelka · AniCura AOI, Švýcarsko",
    about_p1: "MVDr. Ludmila Bičanová je EBVS® evropskou veterinární specialistkou v oblasti veterinární onkologie a radiační onkologie a diplomantkou Evropské koleje veterinárního vnitřního lékařství – společenská zvířata (ECVIM-CA). Je také RCVS uznanou specialistkou v oblasti veterinární onkologie.",
    about_p2: "Jako medicínská ředitelka AniCura AOI – Animal Oncology and Imaging Center v Hünenbergu ve Švýcarsku vede multidisciplinární tým v jednom z předních evropských center veterinární onkologie, které kombinuje špičkovou zobrazovací diagnostiku s komplexní onkologickou léčbou.",
    about_p3: "S více než 15 lety klinických zkušeností v České republice, Rakousku a Švýcarsku se MVDr. Bičanová věnuje poskytování nejvyšší úrovně specializované péče — a provází majitele zvířat s jasností a empatií každým krokem onkologického léčení jejich mazlíčka.",
    stat1_n: "15+", stat1_l: "Let klinické praxe",
    stat2_n: "3",   stat2_l: "Země působení",
    stat3_n: "2",   stat3_l: "Onkologické specializace",
    cred_eyebrow: "Kvalifikace", cred_title: "Tituly a certifikace",
    cred_sub: "Uznáno nejvyššími evropskými a mezinárodními veterinárními orgány",
    c1t: "Dip. ECVIM-CA (Onkologie)", c1b: "Diplomantka Evropské koleje veterinárního vnitřního lékařství – společenská zvířata, onkologická větev",
    c2t: "+ Radiační onkologie",        c2b: "Dodatečná diplomantská kvalifikace v radiační onkologii (ECVIM-CA / ECVDI)",
    c3t: "EBVS® Evropská specialistka", c3b: "Uznání Evropskou radou veterinárních specialistů v oblasti veterinární onkologie a radiační onkologie",
    c4t: "RCVS specialistka",           c4b: "Uznaná specialistka Royal College of Veterinary Surgeons v oblasti veterinární onkologie",
    c5t: "MSc (Klinická onkologie)",    c5b: "Magisterský titul v klinické onkologii",
    c6t: "PhD",                          c6b: "Doktorát z veterinární medicíny / onkologie",
    c7t: "MRCVS",                        c7b: "Člen Royal College of Veterinary Surgeons",
    c8t: "MVDr.",                        c8b: "Doktor veterinární medicíny, Veterinární a farmaceutická univerzita Brno, Česká republika (2009)",
    spec_eyebrow: "Odbornost", spec_title: "Oblasti specializace",
    spec_sub: "Komplexní onkologická péče kombinující medicínské a radiační odborné znalosti",
    s1t: "Medicínská onkologie",     s1b: "Diagnostika, staging a medicínská léčba nádorových onemocnění u společenských zvířat — včetně chemoterapie, imunoterapie a cílené léčby.",
    s2t: "Radiační onkologie",        s2b: "Odborná konzultace a plánování radioterapie, včetně kurativních a paliativních protokolů, v úzké spolupráci s odesílajícími veterináři a radioterapeutickými centry v Evropě.",
    s3t: "Diagnostika lymfomů",       s3b: "Odborná diagnostika a staging psích a kočičích lymfomů se zaměřením na průtokovou cytometrii a molekulární profilování.",
    s4t: "Diagnostická onkologie",    s4b: "Integrace pokročilého zobrazování (CT, MRI, ultrazvuk) s cytologií a histopatologií pro přesnou diagnózu nádoru a plánování léčby.",
    svc_eyebrow: "Služby", svc_title: "Konzultační služby",
    svc_sub: "Personalizovaná specializovaná péče dostupná ve Švýcarsku a České republice",
    sv1t: "Prvotní onkologická konzultace", sv1b: "Komplexní prvotní hodnocení zahrnující anamnézu, fyzikální vyšetření, plánování diagnostiky a staging — s individuálním léčebným plánem.",
    sv2t: "Druhý odborný názor",             sv2b: "Nezávislé odborné posouzení stávajících diagnóz, patologických nálezů a léčebných plánů. Jistota a srozumitelnost při obtížných rozhodnutích.",
    sv3t: "Plánování léčby",                 sv3b: "Důkazně podložené, individualizované léčebné plány integrující nejnovější protokoly v chemoterapii, radioterapii a multimodální onkologické péči.",
    sv4t: "Konzultace radioterapie",         sv4b: "Odborné poradenství ohledně vhodnosti radioterapie, léčebných možností, očekávaných výsledků a koordinace s radioterapeutickými centry v Evropě.",
    sv5t: "Paliativní a podpůrná péče",      sv5b: "Péče zaměřená na kvalitu života u nevyléčitelných pacientů — s důrazem na komfort, kontrolu bolesti a podporu majitelů.",
    sv6t: "Vzdálená konzultace",             sv6b: "Telemedicínské konzultace pro veterináře ve Švýcarsku, České republice a dalších evropských zemích.",
    svc_link: "Zjistit více →",
    career_eyebrow: "Kariéra", career_title: "Profesní dráha",
    career_sub: "Více než 15 let postupně budované odbornosti v oblasti veterinárního vnitřního lékařství a onkologie",
    cr1y: "2009",         cr1t: "Promoce — VFU Brno",               cr1b: "Doktor veterinární medicíny, Veterinární a farmaceutická univerzita Brno, Česká republika",
    cr2y: "2009–2011",    cr2t: "Klinika Jaggy, Brno",               cr2b: "Rotační stáž, poté asistentka v oddělení vnitřní medicíny",
    cr3y: "2011–2015",    cr3t: "Animal Clinic Bílá Hora, Praha",    cr3b: "Klinické zaměření na vnitřní medicínu a onkologii psů a koček na přední soukromé specializované klinice",
    cr4y: "2015–2022",    cr4t: "Vetmeduni Vídeň",                   cr4b: "Oddělení vnitřní medicíny, Klinika malých zvířat; od roku 2017: rezidence v onkologii ECVIM-CA pod vedením prof. Miriam Kleiterové",
    cr5y: "2022",         cr5t: "Diplomantka ECVIM-CA (Onkologie)",  cr5b: "Úspěšné ukončení boardové zkoušky ECVIM-CA v onkologii",
    cr6y: "2022–nyní",    cr6t: "Medicínská ředitelka — AniCura AOI", cr6b: "Vedení klinického týmu v AniCura AOI – Animal Oncology and Imaging Center, Hünenberg, Švýcarsko",
    res_eyebrow: "Věda", res_title: "Vědecké příspěvky",
    res_sub: "Posouvání vědy veterinární onkologie prostřednictvím výzkumu, vzdělávání a publikací",
    r1v: "Veterinary Oncology · BioMed Central",
    r1t: "L-asparagináza u psích lymfomů",
    r1b: "Spoluautorka pilotní studie zkoumající intravenózní podání monomerní L-asparaginázy psům s multicentrickým lymfomem — příspěvek k vývoji nových léčebných protokolů.",
    r2v: "Canine Lymphoma Meeting · Přednášející",
    r2t: "Diagnostika a staging psích lymfomů",
    r2b: "Pozvané sdělení o pokročilých diagnostických metodách pro staging psích lymfomů, včetně průtokové cytometrie a molekulárních diagnostik.",
    r3v: "Frontiers in Veterinary Science · 2025",
    r3t: "Editoriál — Onkologie ve veterinárním lékařství",
    r3b: "Příspěvek k aktuálním výzvám a pokrokům v oblasti veterinární onkologie.",
    roles_eyebrow: "Vedení", roles_title: "Profesní role",
    roles_sub: "Aktivní přispívání k rozvoji veterinární onkologie v Evropě",
    ro1t: "Medicínská ředitelka",                      ro1o: "AniCura AOI – Animal Oncology and Imaging Center, Švýcarsko",
    ro2t: "Předsedkyně výboru pro vzdělávání v radiační onkologii", ro2o: "ECVIM-CA / ECVDI Společný výbor",
    ro3t: "Vedoucí onkologické sekce",                 ro3o: "Česká asociace veterinárních lékařů malých zvířat (ČAVLMZ)",
    ro4t: "Viceprezidentka (od 2018)",                  ro4o: "Česká asociace veterinárních lékařů malých zvířat (ČAVLMZ)",
    loc_eyebrow: "Kde mě najdete", loc_title: "Místa konzultací",
    loc_sub: "Specializované služby dostupné ve Švýcarsku a České republice",
    l1_country: "Švýcarsko", l1_clinic: "AniCura AOI – Animal Oncology and Imaging Center", l1_addr: "Hünenberg, kanton Zug, Švýcarsko",
    l1_desc: "Jedno z předních evropských center veterinární onkologie a zobrazovací diagnostiky nabízející CT, MRI, ultrazvuk, radioterapii a komplexní medicínskou onkologii.",
    l2_country: "Česká republika", l2_clinic: "Specializované konzultace", l2_addr: "Na vyžádání — Česká republika",
    l2_desc: "Konzultace dostupné pro odesílající veterináře a majitele zvířat v České republice. Kontaktujte nás pro informace o termínech.",
    l3_country: "Vzdálená konzultace / Telemedicína", l3_clinic: "Online konzultace", l3_addr: "Dostupné v celé Evropě",
    l3_desc: "Konzultace případů a odborné poradenství na dálku pro veterináře ve Švýcarsku, České republice a dalších evropských zemích.",
    contact_eyebrow: "Kontakt", contact_title: "Objednat konzultaci",
    contact_sub: "Pro odborné žádanky, požadavky na konzultaci nebo obecné dotazy nás prosím kontaktujte prostřednictvím níže uvedeného formuláře.",
    ci1_label: "Hlavní klinika", ci1_val: "AniCura AOI, Hünenberg, Švýcarsko",
    ci2_label: "Konzultace", ci2_val: "Švýcarsko & Česká republika",
    ci3_label: "Jazyky", ci3_val: "English · Deutsch · Čeština",
    ci4_label: "Doba odpovědi", ci4_val: "Do 2 pracovních dnů",
    f_name: "Celé jméno", f_email: "E-mailová adresa", f_phone: "Telefonní číslo (nepovinné)",
    f_type: "Typ konzultace", f_t0: "Vyberte typ konzultace",
    f_t1: "Prvotní onkologická konzultace", f_t2: "Druhý odborný názor",
    f_t3: "Konzultace radioterapie", f_t4: "Vzdálená konzultace / Telemedicína", f_t5: "Jiné",
    f_loc: "Preferované místo", f_l0: "Vyberte místo",
    f_l1: "Švýcarsko", f_l2: "Česká republika", f_l3: "Vzdálená konzultace / Telemedicína",
    f_msg: "Řekněte nám o svém mazlíčkovi a jak vám můžeme pomoci",
    f_submit: "Odeslat dotaz",
    f_note: "Všechny dotazy jsou zpracovávány s přísnou důvěrností. Snažíme se odpovědět do 2 pracovních dnů.",
    ft_tagline: "Evropská veterinární specialistka v onkologii a radiační onkologii",
    ft_nav: "Navigace", ft_contact: "Kontakt", ft_lang: "Jazyk",
    ft_rights: "© 2025 Dr. Ludmila Bičanová. Všechna práva vyhrazena.",
    ft_disclaimer: "Tyto webové stránky slouží pouze k informačním účelům. V případě veterinárních urgencí se okamžitě obraťte na svého veterináře.",
  }
};

let currentLang = 'en';

function setLang(lang) {
  currentLang = lang;
  const t = T[lang];
  document.documentElement.lang = lang === 'cs' ? 'cs' : lang;
  document.title = t.page_title;
  document.querySelectorAll('[data-t]').forEach(el => {
    const key = el.getAttribute('data-t');
    if (t[key] !== undefined) el.textContent = t[key];
  });
  document.querySelectorAll('[data-t-ph]').forEach(el => {
    const key = el.getAttribute('data-t-ph');
    if (t[key] !== undefined) el.placeholder = t[key];
  });
  document.querySelectorAll('.lang-btn, .footer__lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

// Nav scroll behaviour
const nav = document.querySelector('.nav');
window.addEventListener('scroll', () => {
  nav.classList.toggle('scrolled', window.scrollY > 40);
}, { passive: true });

// Mobile nav
const toggle = document.querySelector('.nav__toggle');
const navLinks = document.querySelector('.nav__links');
toggle.addEventListener('click', () => {
  toggle.classList.toggle('open');
  navLinks.classList.toggle('open');
});
navLinks.querySelectorAll('.nav__link').forEach(link => {
  link.addEventListener('click', () => {
    toggle.classList.remove('open');
    navLinks.classList.remove('open');
  });
});

// Language buttons
document.querySelectorAll('[data-lang]').forEach(btn => {
  btn.addEventListener('click', () => setLang(btn.getAttribute('data-lang')));
});

// Scroll reveal
const observer = new IntersectionObserver((entries) => {
  entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('revealed'); observer.unobserve(e.target); } });
}, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });
document.querySelectorAll('.reveal').forEach(el => observer.observe(el));

// Contact form
document.querySelector('.contact-form').addEventListener('submit', e => {
  e.preventDefault();
  const btn = e.target.querySelector('[type=submit]');
  btn.textContent = '✓ Sent';
  btn.style.background = 'var(--primary)';
  btn.disabled = true;
});

// Init
setLang('en');
